[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 30
healthcheckStartPeriod = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
port = 8080

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
PORT = "8080"
RAILWAY_ENVIRONMENT = "production"
STARTUP_DELAY = "60"

[[services]]
name = "worker"
serviceType = "web"

[[services.dependencies]]
name = "redis"
serviceType = "redis" 