[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "python -u -X dev main.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
healthcheckInterval = 15
healthcheckStartPeriod = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
port = 8080

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
PYTHONDONTWRITEBYTECODE = "1"
PYTHONDEVMODE = "1"
PORT = "8080"
RAILWAY_ENVIRONMENT = "production"
STARTUP_DELAY = "30"
LOG_LEVEL = "DEBUG"
REDIS_HOST = "${{Secrets.REDIS_HOST}}"
REDIS_PORT = "6379"
REDIS_PASSWORD = "${{Secrets.REDIS_PASSWORD}}"

[[services]]
name = "worker"
serviceType = "web"

[[services.dependencies]]
name = "redis"
serviceType = "redis" 