[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
port = 8080

[deploy.env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
PORT = "8080"
RAILWAY_ENVIRONMENT = "production"

[[services]]
name = "worker"
serviceType = "web"

[[services.dependencies]]
name = "redis"
serviceType = "redis" 