services:
  - type: worker
    name: tg-secretary-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: USER_ID
        sync: false
      - key: TZ
        value: Europe/Moscow
